version: 2
updates:
  # Disabled until we migrate to remark 13
  # - package-ecosystem: npm
  #   directory: /
  #   schedule:
  #     interval: monthly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
